Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 15
Style/ClassAndModuleChildren:
  Enabled: false
Style/CollectionMethods:
  Enabled: false
Style/DotPosition:
  EnforcedStyle: leading
Style/FormatString:
  Enabled: false
Style/AndOr:
  EnforcedStyle: conditionals
Style/Not:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: single_quotes
Lint/ShadowingOuterLocalVariable:
  Enabled: false
AllCops:
  RunRailsCops: true
  Exclude:
  - 'bin/**/*'
  - 'config/**/*'
  - 'db/schema.rb'
  - 'node_modules/**/*'
  - 'tmp/**/*'
  - 'vendor/**/*'
