inherit_from:
  - https://raw.githubusercontent.com/moneyadviceservice/mas-standards/heroku-migration/.rubocop.yml
  - .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

# Project specific settings
AllCops:
  Exclude:
    - 'lib/fca/**/*'

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false
