inherit_from:
  - https://raw.githubusercontent.com/moneyadviceservice/mas-standards/master/.rubocop.yml
  - .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

# Project specific settings
AllCops:
  Exclude:
    - 'lib/fca/**/*'

# Once we upgrade rubocop we should be able to remove this
Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - development
    - local
    - test
