default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: utf8
  reconnect: true

development:
  <<: *default
  database: rad_development

test:
  <<: *default
  database: rad_test

production:
  <<: *default
  database: rad_production
  username: rad
  password: <%= ENV['RAD_DATABASE_PASSWORD'] %>
