default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: postgres

development:
  <<: *default
  database: rad_development

test:
  <<: *default
  database: rad_test
  <% if ENV['CI'] == 'true' %>
  username: <%= ENV.fetch('POSTGRES_USER') { 'postgres ' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { 'postgres ' } %>
  <% end %>

production:
  <<: *default
  database: rad_production
  username: rad
  password: <%= ENV['RAD_DATABASE_PASSWORD'] %>
