#!/bin/bash -l

set -e

if [ -f /.dockerenv ]; then
    source ~/.bashrc
    rvm use default
    mv config/database{-jenkins,}.yml
fi

export RAILS_ENV=test
export BUNDLE_WITHOUT=development:build

exit_code=0

function run {
    declare -a tests_command=("$@")

    echo ''
    echo "=== Running \`${tests_command[*]}\`"
    if ! ${tests_command[*]}; then
        echo "=== These tests failed."
        exit_code=1
    fi
}

function info {
    declare -a info_command=("$@")
    echo ''
    echo "=== Running for informational purposes \`${info_command[*]}\`"
    if ! ${info_command[*]}; then
        echo "== This test has errors and/or warnings. Please review results"
    fi
}

run npm install --quiet
run bundle install --quiet
run bundle update brakeman --quiet
run bundle exec bowndler install --allow-root
run mv config/cloud_storage{.example,}.yml
run bundle exec rake db:drop db:setup
run bundle exec rspec
run bundle exec ./node_modules/.bin/karma start spec/javascripts/karma.conf.js --single-run
run bundle exec cucumber
run bundle exec rubocop -DS
info bundle exec brakeman -q --no-pager --ensure-latest

if [ -f /.dockerenv ]; then
  run bundle exec danger --dangerfile=jenkins/Dangerfile --verbose
fi

exit "$exit_code"
