#!/bin/bash
# Useful for testing in docker locally
set -e
export COMPOSE_PROJECT_NAME=rad
image_name="rad_rails_1"

docker-compose pull
docker-compose build --force-rm
docker-compose up -d

# docker logs will only run until the container exits
( docker logs --follow "$image_name" )&

exit_code="$( docker wait "$image_name" )"
docker-compose down

exit "$exit_code"
